// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './server'

export type PageName = 'endpoint/show' | 'home' | 'privacy' | 'terms'

declare module '@hono/inertia' {
  interface InertiaPages {
    'endpoint/show': unknown
    'home': unknown
    'privacy': unknown
    'terms': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
